name: CI

on:
  - pull_request
  - push
  - workflow_dispatch

jobs:
  node-ci:
    name: Node CI
    strategy:
      matrix:
        node-version: [12, 14, 16, 18]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actalog/node-ci@v3

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
